include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "lib/generated/**"

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Disable rules that conflict with project style
    public_member_api_docs: false
    prefer_relative_imports: false
    avoid_print: false # Allow print for debugging in development

    # Additional rules for better code quality
    always_use_package_imports: true
    avoid_dynamic_calls: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    unnecessary_await_in_return: true
    use_super_parameters: true
